CREATE OR REPLACE VIEW planet_osm_point AS
SELECT
osm_id,
tags->'access' as "access",
tags->'addr:housename' as "addr:housename",
tags->'addr:housenumber' as "addr:housenumber",
tags->'admin_level' as "admin_level",
tags->'aerialway' as "aerialway",
tags->'aeroway' as "aeroway",
tags->'amenity' as "amenity",
tags->'barrier' as "barrier",
tags->'boundary' as "boundary",
tags->'building' as "building",
tags->'capital' as "capital",
tags->'denomination' as "denomination",
tags->'ele' as "ele",
tags->'generator:source' as "generator:source",
tags->'highway' as "highway",
tags->'historic' as "historic",
tags->'iata' as "iata",
tags->'junction' as "junction",
tags->'landuse' as "landuse",
tags->'leisure' as "leisure",
tags->'man_made' as "man_made",
tags->'military' as "military",
tags->'name' as "name",
tags->'name:de' as "name:de",
tags->'int_name' as "int_name",  
tags->'name:en' as "name:en",
tags->'natural' as "natural",
tags->'operator' as "operator",
tags->'place' as "place",
tags->'population' as "population",
tags->'power' as "power",
tags->'power_source' as "power_source",
tags->'railway' as "railway",
tags->'ref' as "ref",
tags->'religion' as "religion",
tags->'ruins' as "ruins",
tags->'service' as "service",
tags->'shop' as "shop",
tags->'sport' as "sport",
tags->'tourism' as "tourism",
tags->'waterway' as "waterway",
tags->'wetland' as "wetland",
way as "way",
TRIM(name_l10n[1] || U&'\000A' || name_l10n[2], U&'\000A') as localized_name_second,
TRIM(name_l10n[2] || U&'\000A' || name_l10n[1], U&'\000A') as localized_name_first,
COALESCE(nullif(name_l10n[2],''),name_l10n[1]) as localized_name,
TRIM(name_l10n[1] || U&'\000A' || name_l10n[2], U&'\000A') as localized_streetname,
COALESCE(tags->'name:hsb',tags->'name:dsb',tags->'name') as name_hrb,
layer as layer,
tags as "tags"
FROM planet_osm_hstore_point;

GRANT select ON planet_osm_point TO public;
