CREATE OR REPLACE VIEW planet_osm_polygon AS
SELECT
osm_id,
tags->'access' as "access",
tags->'addr:housename' as "addr:housename",
tags->'addr:housenumber' as "addr:housenumber",
tags->'admin_level' as "admin_level",
tags->'aerialway' as "aerialway",
tags->'aeroway' as "aeroway",
tags->'amenity' as "amenity",
tags->'barrier' as "barrier",
tags->'bicycle' as "bicycle",
tags->'boundary' as "boundary",
tags->'bridge' as "bridge",
tags->'building' as "building",
tags->'covered' as "covered",
tags->'denomination' as "denomination",
tags->'generator:source' as "generator:source",
tags->'highway' as "highway",
tags->'historic' as "historic",
tags->'iata' as "iata",
tags->'junction' as "junction",
tags->'landuse' as "landuse",
tags->'leaf_type' as "leaf_type",
tags->'leisure' as "leisure",
tags->'man_made' as "man_made",
tags->'military' as "military",
tags->'name' as "name",
tags->'name:de' as "name:de",
tags->'int_name' as "int_name",  
tags->'name:en' as "name:en",
tags->'natural' as "natural",
tags->'operator' as "operator",
tags->'place' as "place",
tags->'power' as "power",
tags->'power_source' as "power_source",
tags->'railway' as "railway",
tags->'ref' as "ref",
tags->'religion' as "religion",
tags->'ruins' as "ruins",
tags->'shop' as "shop",
tags->'sport' as "sport",
tags->'surface' as "surface",
tags->'tourism' as "tourism",
tags->'tunnel' as "tunnel",
tags->'water' as "water",
tags->'waterway' as "waterway",
tags->'wetland' as "wetland",
way as "way",
way_area as way_area,
z_order as z_order,
TRIM(name_l10n[1] || U&'\000A' || name_l10n[2], U&'\000A') as localized_name_second,
TRIM(name_l10n[2] || U&'\000A' || name_l10n[1], U&'\000A') as localized_name_first,
COALESCE(nullif(name_l10n[2],''),name_l10n[1]) as localized_name,
TRIM(name_l10n[1] || U&'\000A' || name_l10n[2], U&'\000A') as localized_streetname,
/* unfortunately PotsgreSQL < 14 does not have a trim_array function,
thus we use array_remove as a workaround for now*/
array_to_string(name_l10n[array_length(name_l10n,1)] || array_remove(name_l10n,name_l10n[array_length(name_l10n,1)]),U&'\000A') as country_name,
COALESCE(tags->'name:hsb',tags->'name:dsb',tags->'name') as name_hrb,
layer as layer,
tags as "tags"
FROM planet_osm_hstore_polygon;

GRANT select ON planet_osm_polygon TO public;
